/**
 * Seed REAL scholarship data — verified against official portals.
 *
 * Data sourced from web research (see /tmp/scholarship-research-report).
 * Every record carries: provider, official application URL, official source URL,
 * and a lastVerifiedAt timestamp. Where an exact deadline varies year to year,
 * typicalWindow is set and isExactDateConfirmed is false.
 *
 * Usage:
 *   node src/scripts/seedScholarships.js            # add missing
 *   node src/scripts/seedScholarships.js --force    # replace all
 *   node src/scripts/seedScholarships.js --refresh-dates  # only refresh verified dates
 */

import mongoose from "mongoose";
import Scholarship from "../models/Scholarship.js";
import Admin from "../models/Admin.js";
import connectDB from "../config/db.js";

const logger = {
  info: (msg, data = {}) => console.log(`[INFO] ${msg}`, data),
  error: (msg, error = {}) => console.error(`[ERROR] ${msg}`, error),
  success: (msg) => console.log(`✓ ${msg}`),
  warn: (msg) => console.warn(`⚠ ${msg}`),
};

// Verified date — every record is stamped with this so the admin can
// later bulk-verify against a known baseline.
const VERIFIED_AT = new Date("2026-10-07T00:00:00.000Z");

// ─── 28 verified scholarships ──────────────────────────────────────────

const getScholarships = () => [
  // ============ NSP (NATIONAL SCHOLARSHIP PORTAL) ============
  {
    name: "Pre-Matric Scholarship Scheme (SC/ST/OBC & Minorities)",
    shortDescription:
      "Financial assistance for students of notified categories studying in Classes IX–X in recognised Indian institutions, processed via the National Scholarship Portal.",
    description:
      "Two parallel schemes run under this umbrella: one by the Ministry of Social Justice & Empowerment (SC/ST/OBC) and one by the Ministry of Minority Affairs (Minorities). The award typically includes a monthly maintenance allowance plus an annual book/course-fee allowance. Amounts are revised periodically — verify the latest slab on the official NSP scheme PDF.",
    scholarshipType: "category",
    category: "central_government",
    tags: ["nsp", "pre-matric", "sc", "st", "obc", "minority"],
    amount: { min: 600, max: 1200, currency: "INR", frequency: "annual", note: "Maintenance + book allowance; verify latest slab" },
    eligibility: {
      educationLevels: ["class_10th"],
      streams: ["any"],
      courses: [],
      categories: ["sc", "st", "obc", "minority"],
      gender: "any",
      states: [],
      nationality: "Indian",
      minPercentage: null,
      maxFamilyIncome: 250000,
      minAge: null,
      maxAge: null,
      disability: false,
      otherRequirements: "Studying in Class IX or X in a recognised Indian institution",
    },
    deadline: {
      applicationStartDate: null,
      applicationEndDate: null,
      typicalWindow: "October – December each year (verify on NSP)",
      isRecurring: true,
      isExactDateConfirmed: false,
    },
    requiredDocuments: [
      "Aadhaar card",
      "Income Certificate",
      "Caste / Community Certificate",
      "Bank passbook",
      "Fee receipt",
      "Bonafide certificate",
      "Passport-size photograph",
    ],
    applicationProcess:
      "Register on the National Scholarship Portal (scholarships.gov.in) as a new user, fill in the application form, upload the required documents, and submit before the cycle deadline. Renew annually.",
    source: {
      sourceName: "National Scholarship Portal (Ministry of Social Justice & Empowerment; Ministry of Minority Affairs)",
      sourceUrl: "https://scholarships.gov.in/All-Scholarships",
      officialApplicationUrl: "https://scholarships.gov.in/",
      sourceType: "government",
      lastVerifiedAt: VERIFIED_AT,
      contactPhone: "0120-6619540 (NSP helpdesk)",
      contactEmail: "",
      contactWebsite: "https://scholarships.gov.in/",
    },
    status: "active",
    isFeatured: true,
    displayOrder: 10,
    priority: 90,
    keywords: ["pre-matric", "sc st obc", "minority", "nsp", "class 9", "class 10"],
    notes: "Two parallel schemes — confirm which Ministry administers the specific category you belong to before applying.",
  },
  {
    name: "Post-Matric Scholarship for SC / ST / OBC",
    shortDescription:
      "Post-matriculation financial assistance for SC, ST and OBC students from Class 11 onwards, covering tuition fees, maintenance allowance, study tour and thesis printing.",
    description:
      "Centrally-sponsored scheme implemented by states/UTs. Course fee + maintenance allowance (slab-wise by course) + other components. Day-scholar rates are lower than hosteller rates. The OBC/EBC/DNT component has a separate sub-scheme.",
    scholarshipType: "category",
    category: "central_government",
    tags: ["nsp", "post-matric", "sc", "st", "obc"],
    amount: { min: 2760, max: 14400, currency: "INR", frequency: "annual", note: "Maintenance allowance slab; tuition fee reimbursed" },
    eligibility: {
      educationLevels: ["class_12th", "diploma", "bachelor", "master", "phd"],
      streams: ["any"],
      courses: [],
      categories: ["sc", "st", "obc"],
      gender: "any",
      states: [],
      nationality: "Indian",
      minPercentage: 50,
      maxFamilyIncome: 250000,
      minAge: null,
      maxAge: null,
      disability: false,
      otherRequirements: "Studying in a recognised institution post-Class 10",
    },
    deadline: {
      applicationStartDate: null,
      applicationEndDate: null,
      typicalWindow: "October – December each year (verify on NSP)",
      isRecurring: true,
      isExactDateConfirmed: false,
    },
    requiredDocuments: [
      "Aadhaar",
      "Caste Certificate",
      "Income Certificate",
      "Previous year mark sheet",
      "Fee receipt",
      "Bank passbook",
      "Bonafide certificate",
    ],
    applicationProcess:
      "Apply on the National Scholarship Portal. State scholarship officer verifies; DBT transfers funds to the student's bank account.",
    source: {
      sourceName: "National Scholarship Portal (Ministry of Social Justice & Empowerment)",
      sourceUrl: "https://scholarships.gov.in/public/schemeGuidelines/POST_MATRIC_OBC_GUIDELINES.pdf",
      officialApplicationUrl: "https://scholarships.gov.in/",
      sourceType: "government",
      lastVerifiedAt: VERIFIED_AT,
      contactPhone: "0120-6619540",
      contactEmail: "",
      contactWebsite: "https://scholarships.gov.in/",
    },
    status: "active",
    isFeatured: true,
    displayOrder: 11,
    priority: 92,
    keywords: ["post-matric", "sc", "st", "obc", "nsp", "tuition fee", "maintenance allowance"],
  },
  {
    name: "Merit-cum-Means Scholarship for Professional & Technical Courses (Minority Affairs)",
    shortDescription:
      "Financial assistance for students from notified minority communities (Muslim, Christian, Sikh, Buddhist, Parsi, Jain) pursuing professional/technical courses at UG and PG level.",
    description:
      "Covers full course fee (subject to ceiling) plus a maintenance allowance: ₹5,000/yr (Class IX–X), ₹6,000/yr (XI–XII), ₹10,000/yr (UG/PG). One of the most-utilized NSP merit-cum-means schemes; only one merit-based NSP application per student is permitted per year.",
    scholarshipType: "merit_cum_need",
    category: "central_government",
    tags: ["nsp", "minority", "merit", "professional", "technical"],
    amount: { min: 5000, max: 25000, currency: "INR", frequency: "annual", note: "Course fee (ceiling) + maintenance allowance" },
    eligibility: {
      educationLevels: ["bachelor", "master"],
      streams: ["engineering", "medical", "law", "management", "any"],
      courses: ["Professional & technical courses at UG/PG"],
      categories: ["minority"],
      gender: "any",
      states: [],
      nationality: "Indian",
      minPercentage: 50,
      maxFamilyIncome: 250000,
      minAge: null,
      maxAge: null,
      disability: false,
      otherRequirements: "From a notified minority community",
    },
    deadline: {
      applicationStartDate: null,
      applicationEndDate: null,
      typicalWindow: "October – December each year (verify on NSP)",
      isRecurring: true,
      isExactDateConfirmed: false,
    },
    requiredDocuments: [
      "Aadhaar",
      "Minority Community Certificate",
      "Income Certificate",
      "Mark sheets",
      "Fee receipt",
      "Bank passbook",
      "Bonafide certificate",
    ],
    applicationProcess: "Apply via National Scholarship Portal under the Ministry of Minority Affairs schemes.",
    source: {
      sourceName: "National Scholarship Portal (Ministry of Minority Affairs)",
      sourceUrl: "https://scholarships.gov.in/All-Scholarships",
      officialApplicationUrl: "https://scholarships.gov.in/",
      sourceType: "government",
      lastVerifiedAt: VERIFIED_AT,
      contactPhone: "0120-6619540",
      contactEmail: "",
      contactWebsite: "https://scholarships.gov.in/",
    },
    status: "active",
    isFeatured: true,
    displayOrder: 12,
    priority: 88,
    keywords: ["minority", "merit", "means", "professional", "technical", "nsp"],
  },
  {
    name: "Prime Minister's Scholarship Scheme (PMSS) — Wards of Ex-Servicemen / Ex-Coast Guard",
    shortDescription:
      "Scholarship for wards and widows of Ex-Servicemen and Ex-Coast Guard personnel pursuing higher education in India.",
    description:
      "5,500 scholarships awarded each year (2,750 boys + 2,750 girls). Increased amounts (from prior ₹2,000/₹2,250 slabs) — confirm latest on the KSB portal before applying.",
    scholarshipType: "merit",
    category: "central_government",
    tags: ["pmss", "defence", "ex-servicemen", "ksb", "merit"],
    amount: { min: 30000, max: 36000, currency: "INR", frequency: "annual", note: "₹2,500/mo boys, ₹3,000/mo girls" },
    eligibility: {
      educationLevels: ["diploma", "bachelor", "master"],
      streams: ["any"],
      courses: [],
      categories: ["any"],
      gender: "any",
      states: [],
      nationality: "Indian",
      minPercentage: 60,
      maxFamilyIncome: null,
      minAge: null,
      maxAge: null,
      disability: false,
      otherRequirements: "Ward or widow of Ex-Serviceman / Ex-Coast Guard personnel",
    },
    deadline: {
      applicationStartDate: null,
      applicationEndDate: null,
      typicalWindow: "September – December each year (verify on KSB)",
      isRecurring: true,
      isExactDateConfirmed: false,
    },
    requiredDocuments: [
      "Ex-Serviceman Certificate",
      "Discharge Book",
      "Mark sheets",
      "Bonafide Certificate",
      "Bank passbook",
      "Aadhaar",
    ],
    applicationProcess: "Apply via the Kendriya Sainik Board (KSB) portal at ksb.gov.in.",
    source: {
      sourceName: "Department of Ex-Servicemen Welfare, Ministry of Defence",
      sourceUrl: "https://desw.gov.in/en/prime-ministers-scholarship-scheme-pmss",
      officialApplicationUrl: "https://ksb.gov.in/",
      sourceType: "government",
      lastVerifiedAt: VERIFIED_AT,
      contactPhone: "KSB Helpline (varies by state)",
      contactEmail: "",
      contactWebsite: "https://desw.gov.in/",
    },
    status: "active",
    isFeatured: false,
    displayOrder: 20,
    priority: 70,
    keywords: ["pmss", "defence", "ex-servicemen", "ksb"],
  },
  {
    name: "Central Sector Scholarship Scheme of Top Class Education (SC Students)",
    shortDescription:
      "Full financial support for SC students pursuing top-class professional courses at notified premier institutions (IITs, IIMs, NLUs, medical colleges).",
    description:
      "Covers full tuition fees + living expenses + books/equipment grant (₹2,00,000/annum tuition ceiling for private institutions). Active since June 2007. Distinct from the 'CSSS for College/University Students' scheme run by the Ministry of Education.",
    scholarshipType: "category",
    category: "central_government",
    tags: ["scss", "top class", "sc", "iit", "iim", "nlu"],
    amount: { min: 200000, max: 600000, currency: "INR", frequency: "full_course", note: "Full tuition + living expenses + equipment" },
    eligibility: {
      educationLevels: ["bachelor", "master"],
      streams: ["engineering", "medical", "law", "management", "any"],
      courses: ["Premier institute courses (IIT, IIM, NLU, etc.)"],
      categories: ["sc"],
      gender: "any",
      states: [],
      nationality: "Indian",
      minPercentage: null,
      maxFamilyIncome: 800000,
      minAge: null,
      maxAge: null,
      disability: false,
      otherRequirements: "Admitted to a notified premier institution",
    },
    deadline: {
      applicationStartDate: null,
      applicationEndDate: null,
      typicalWindow: "Verify annually on NSP / Ministry of Social Justice portal",
      isRecurring: true,
      isExactDateConfirmed: false,
    },
    requiredDocuments: [
      "SC Caste Certificate",
      "Income Certificate",
      "Admission letter to premier institution",
      "Mark sheets",
      "Bank passbook",
      "Aadhaar",
    ],
    applicationProcess: "Apply through NSP; verification by the institution and the Ministry of Social Justice & Empowerment.",
    source: {
      sourceName: "Ministry of Social Justice and Empowerment",
      sourceUrl: "https://socialjustice.gov.in/schemes/29",
      officialApplicationUrl: "https://scholarships.gov.in/",
      sourceType: "government",
      lastVerifiedAt: VERIFIED_AT,
      contactPhone: "",
      contactEmail: "",
      contactWebsite: "https://socialjustice.gov.in/",
    },
    status: "active",
    isFeatured: true,
    displayOrder: 13,
    priority: 87,
    keywords: ["top class", "scss", "sc", "iit", "iim", "premier institute"],
  },
  {
    name: "Central Sector Scholarship Scheme for College & University Students (PM-USP / CSSS)",
    shortDescription:
      "Merit-cum-means scholarship for students who scored above the 80th percentile in Class 12 and are pursuing regular, full-time degree courses.",
    description:
      "Also called Pradhan Mantri Uchchatar Shiksha Protsahan (PM-USP). Slab-wise award: ₹10,000 per annum at graduation level, up to ₹20,000 for professional/technical courses at degree+PG level. PM-USP CSSS is the only merit-based NSP scheme — a student may apply for one merit-based + one or more welfare-based schemes per year.",
    scholarshipType: "merit",
    category: "central_government",
    tags: ["nsp", "csss", "pm-usp", "merit", "class 12", "80th percentile"],
    amount: { min: 10000, max: 20000, currency: "INR", frequency: "annual", note: "Slab-wise by course level" },
    eligibility: {
      educationLevels: ["bachelor", "master"],
      streams: ["any"],
      courses: [],
      categories: ["any"],
      gender: "any",
      states: [],
      nationality: "Indian",
      minPercentage: 80,
      maxFamilyIncome: 450000,
      minAge: null,
      maxAge: null,
      disability: false,
      otherRequirements: "Above 80th percentile in Class 12 board exam (eligible from Class 12 itself in some slabs)",
    },
    deadline: {
      applicationStartDate: null,
      applicationEndDate: null,
      typicalWindow: "October – December each year (verify on NSP)",
      isRecurring: true,
      isExactDateConfirmed: false,
    },
    requiredDocuments: [
      "Class 12 Marksheet",
      "Income Certificate",
      "Bonafide Certificate",
      "Fee receipt",
      "Aadhaar",
      "Bank passbook",
    ],
    applicationProcess: "Apply through the National Scholarship Portal under the Department of Higher Education (Ministry of Education) scheme.",
    source: {
      sourceName: "Department of Higher Education, Ministry of Education",
      sourceUrl: "https://scholarships.gov.in/public/schemeGuidelines/FAQ_DOHE_CSSS.pdf",
      officialApplicationUrl: "https://scholarships.gov.in/",
      sourceType: "government",
      lastVerifiedAt: VERIFIED_AT,
      contactPhone: "0120-6619540",
      contactEmail: "",
      contactWebsite: "https://www.education.gov.in/",
    },
    status: "active",
    isFeatured: true,
    displayOrder: 14,
    priority: 91,
    keywords: ["csss", "pm-usp", "merit", "class 12", "80th percentile", "nsp"],
  },
  {
    name: "INSPIRE Scholarship for Higher Education (SHE)",
    shortDescription:
      "Scholarship for top-performing Class 12 students pursuing undergraduate and postgraduate studies in natural/basic sciences at recognised Indian institutions.",
    description:
      "Award: ₹80,000 per annum + ₹20,000 mentorship grant = ~₹1,00,000 per year (revised upward from the prior ₹60,000 figure). ~10,000 scholarships per year. Managed by the Department of Science & Technology.",
    scholarshipType: "merit",
    category: "central_government",
    tags: ["inspire", "dst", "science", "top 1%", "she", "class 12"],
    amount: { min: 80000, max: 100000, currency: "INR", frequency: "annual", note: "₹80,000 + ₹20,000 mentorship" },
    eligibility: {
      educationLevels: ["bachelor", "master"],
      streams: ["pcm", "any"],
      courses: ["B.Sc.", "B.S.", "Integrated M.Sc.", "M.S. in basic & applied sciences"],
      categories: ["any"],
      gender: "any",
      states: [],
      nationality: "Indian",
      minPercentage: 65,
      maxFamilyIncome: null,
      minAge: null,
      maxAge: null,
      disability: false,
      otherRequirements: "Top 1% in Class 12 board exam OR top 10,000 rank in JEE Main/Advanced/NEET",
    },
    deadline: {
      applicationStartDate: null,
      applicationEndDate: null,
      typicalWindow: "April – June each year (verify on INSPIRE portal)",
      isRecurring: true,
      isExactDateConfirmed: false,
    },
    requiredDocuments: [
      "Class 12 marksheet",
      "JEE / NEET rank letter (if applicable)",
      "College admission proof",
      "ID",
      "Bank details",
    ],
    applicationProcess: "Apply online at online-inspire.gov.in with academic records and proof of admission.",
    source: {
      sourceName: "Department of Science & Technology (DST), Ministry of Science & Technology",
      sourceUrl: "https://dst.gov.in/inspire-scheme-innovation-science-pursuit-inspired-research",
      officialApplicationUrl: "https://www.online-inspire.gov.in/",
      sourceType: "government",
      lastVerifiedAt: VERIFIED_AT,
      contactPhone: "",
      contactEmail: "inspire-dst@nic.in",
      contactWebsite: "https://www.online-inspire.gov.in/",
    },
    status: "active",
    isFeatured: true,
    displayOrder: 15,
    priority: 89,
    keywords: ["inspire", "she", "dst", "science", "top 1%", "class 12"],
  },
  {
    name: "National Talent Search Examination (NTSE) Scholarship",
    shortDescription:
      "Scholarship awarded to Class 10 students who qualify the national-level NTSE conducted by NCERT, with continued support through higher secondary and undergraduate/postgraduate levels.",
    description:
      "Two-stage exam — Mental Ability Test (MAT) and Scholastic Aptitude Test (SAT). ₹1,250/month at Classes XI–XII; higher rates at UG/PG level. Open only to Indian nationals studying in Class 10.",
    scholarshipType: "merit",
    category: "central_government",
    tags: ["ntse", "ncert", "talent search", "class 10"],
    amount: { min: 15000, max: 24000, currency: "INR", frequency: "annual", note: "₹1,250/month; higher at UG/PG" },
    eligibility: {
      educationLevels: ["class_10th", "class_12th", "bachelor", "master", "phd"],
      streams: ["any"],
      courses: [],
      categories: ["any"],
      gender: "any",
      states: [],
      nationality: "Indian",
      minPercentage: null,
      maxFamilyIncome: null,
      minAge: null,
      maxAge: null,
      disability: false,
      otherRequirements: "Qualifying marks: 40% General/OBC; 32% SC/ST/PwD",
    },
    deadline: {
      applicationStartDate: null,
      applicationEndDate: null,
      typicalWindow: "Stage-I November; Stage-II February–June (verify annually)",
      isRecurring: true,
      isExactDateConfirmed: false,
    },
    requiredDocuments: [
      "Stage-I/II Admit Card",
      "Class 10 marksheet",
      "School Bonafide",
      "ID proof",
    ],
    applicationProcess:
      "Stage-I conducted by states/UTs; Stage-II conducted by NCERT. Apply via your school for Stage-I; NCERT handles Stage-II for shortlisted candidates.",
    source: {
      sourceName: "National Council of Educational Research and Training (NCERT)",
      sourceUrl: "https://ncert.nic.in/national-talent-examination.php",
      officialApplicationUrl: "https://ncert.nic.in/national-talent-examination.php",
      sourceType: "government",
      lastVerifiedAt: VERIFIED_AT,
      contactPhone: "",
      contactEmail: "",
      contactWebsite: "https://ncert.nic.in/",
    },
    status: "active",
    isFeatured: false,
    displayOrder: 25,
    priority: 70,
    keywords: ["ntse", "ncert", "talent search", "scholarship exam", "class 10"],
  },
  {
    name: "AICTE Pragati Scholarship Scheme for Girl Students",
    shortDescription:
      "Scholarship for girl students admitted to AICTE-approved institutions for Degree/Diploma technical courses.",
    description:
      "Award: ₹50,000 per annum, every year of study. Up to 2 girls per family can apply. 15% SC, 7.5% ST, 27% OBC reservations apply within the scheme.",
    scholarshipType: "gender",
    category: "central_government",
    tags: ["aicte", "pragati", "girls", "women", "technical"],
    amount: { min: 50000, max: 50000, currency: "INR", frequency: "annual" },
    eligibility: {
      educationLevels: ["diploma", "bachelor"],
      streams: ["engineering"],
      courses: ["AICTE-approved technical courses"],
      categories: ["any", "women"],
      gender: "female_only",
      states: [],
      nationality: "Indian",
      minPercentage: 60,
      maxFamilyIncome: 600000,
      minAge: null,
      maxAge: null,
      disability: false,
      otherRequirements: "Admitted to AICTE-approved institution; up to 2 girls per family",
    },
    deadline: {
      applicationStartDate: null,
      applicationEndDate: null,
      typicalWindow: "October – November each year (verify on AICTE fellowship portal)",
      isRecurring: true,
      isExactDateConfirmed: false,
    },
    requiredDocuments: [
      "Class 12 marksheet",
      "Admission letter",
      "Income Certificate",
      "Bank passbook",
      "Aadhaar",
    ],
    applicationProcess: "Apply through the AICTE fellowship portal at fellowship.aicte.gov.in.",
    source: {
      sourceName: "All India Council for Technical Education (AICTE)",
      sourceUrl: "https://aicte.gov.in/index.php/schemes/students-development-schemes/Pragati/General-Instructions",
      officialApplicationUrl: "https://fellowship.aicte.gov.in/",
      sourceType: "government",
      lastVerifiedAt: VERIFIED_AT,
      contactPhone: "",
      contactEmail: "",
      contactWebsite: "https://aicte.gov.in/",
    },
    status: "active",
    isFeatured: true,
    displayOrder: 16,
    priority: 86,
    keywords: ["aicte", "pragati", "girls", "women", "technical", "engineering"],
  },
  {
    name: "AICTE Saksham Scholarship Scheme",
    shortDescription:
      "Scholarship for students with disabilities (PwD) of 40%+ pursuing AICTE-approved Degree/Diploma technical courses.",
    description: "Award: ₹50,000 per annum. Tracked separately from Pragati but uses the same portal.",
    scholarshipType: "disability",
    category: "central_government",
    tags: ["aicte", "saksham", "pwd", "disability", "technical"],
    amount: { min: 50000, max: 50000, currency: "INR", frequency: "annual" },
    eligibility: {
      educationLevels: ["diploma", "bachelor"],
      streams: ["engineering"],
      courses: ["AICTE-approved technical courses"],
      categories: ["pwd"],
      gender: "any",
      states: [],
      nationality: "Indian",
      minPercentage: null,
      maxFamilyIncome: 600000,
      minAge: null,
      maxAge: null,
      disability: true,
      otherRequirements: "40%+ disability",
    },
    deadline: {
      applicationStartDate: null,
      applicationEndDate: null,
      typicalWindow: "October – November each year (verify on AICTE fellowship portal)",
      isRecurring: true,
      isExactDateConfirmed: false,
    },
    requiredDocuments: [
      "PwD Certificate (40%+ disability)",
      "Income Certificate",
      "Admission letter",
      "Mark sheet",
      "Aadhaar",
    ],
    applicationProcess: "Apply through the AICTE fellowship portal at fellowship.aicte.gov.in.",
    source: {
      sourceName: "All India Council for Technical Education (AICTE)",
      sourceUrl: "https://aicte.gov.in/index.php/schemes/students-development-schemes",
      officialApplicationUrl: "https://fellowship.aicte.gov.in/",
      sourceType: "government",
      lastVerifiedAt: VERIFIED_AT,
      contactPhone: "",
      contactEmail: "",
      contactWebsite: "https://aicte.gov.in/",
    },
    status: "active",
    isFeatured: false,
    displayOrder: 30,
    priority: 75,
    keywords: ["aicte", "saksham", "pwd", "disability", "technical"],
  },
  {
    name: "UGC NET Junior Research Fellowship (JRF)",
    shortDescription:
      "Qualifying exam for admission to Ph.D. and research programs; JRF category qualifies for monthly fellowship at Indian institutions.",
    description:
      "Award: ₹37,000/month (JRF, first 2 years); ₹42,000/month (SRF after upgrade); annual contingent grant ~₹20,000 + HRA. Test conducted by NTA twice a year. Only 'JRF' (not Lectureship) qualifies for the fellowship.",
    scholarshipType: "research",
    category: "research_fellowship",
    tags: ["ugc", "net", "jrf", "phd", "research"],
    amount: { min: 444000, max: 504000, currency: "INR", frequency: "annual", note: "₹37k/mo JRF; ₹42k/mo SRF + HRA + contingent" },
    eligibility: {
      educationLevels: ["phd"],
      streams: ["any"],
      courses: [],
      categories: ["any"],
      gender: "any",
      states: [],
      nationality: "Indian",
      minPercentage: 55,
      maxFamilyIncome: null,
      minAge: null,
      maxAge: 30,
      disability: false,
      otherRequirements: "Master's degree; must qualify UGC-NET JRF (not Lectureship-only)",
    },
    deadline: {
      applicationStartDate: null,
      applicationEndDate: null,
      typicalWindow: "June – December each year (test held twice a year)",
      isRecurring: true,
      isExactDateConfirmed: false,
    },
    requiredDocuments: [
      "Master's degree certificate",
      "Category certificate (if applicable)",
      "ID",
      "Photograph",
    ],
    applicationProcess: "Register on the NTA UGC-NET portal; appear for the exam.",
    source: {
      sourceName: "University Grants Commission (UGC)",
      sourceUrl: "https://www.ugc.gov.in/",
      officialApplicationUrl: "https://ugcnet.nta.ac.in/",
      sourceType: "government",
      lastVerifiedAt: VERIFIED_AT,
      contactPhone: "",
      contactEmail: "",
      contactWebsite: "https://www.ugc.gov.in/",
    },
    status: "active",
    isFeatured: true,
    displayOrder: 17,
    priority: 90,
    keywords: ["ugc", "net", "jrf", "phd", "research fellowship", "lectureship"],
  },
  {
    name: "CSIR NET Junior Research Fellowship (JRF)",
    shortDescription:
      "JRF awarded to candidates qualifying the CSIR-UGC NET exam in Science & Engineering streams for pursuing Ph.D. in Indian institutions.",
    description:
      "Award: ₹37,000/month (JRF first 2 years); ₹42,000/month (SRF after upgrade); ₹20,000/year contingent grant; HRA as per norms. Age limit: max 28 years; SC/ST +5 years, OBC +3 years, PwD +10 years. Only Indian citizens residing in India are eligible.",
    scholarshipType: "research",
    category: "research_fellowship",
    tags: ["csir", "net", "jrf", "phd", "research", "science"],
    amount: { min: 444000, max: 504000, currency: "INR", frequency: "annual", note: "₹37k/mo JRF; ₹42k/mo SRF" },
    eligibility: {
      educationLevels: ["phd"],
      streams: ["pcm"],
      courses: ["Life Sciences", "Chemical Sciences", "Earth Sciences", "Physical Sciences", "Mathematical Sciences"],
      categories: ["any"],
      gender: "any",
      states: [],
      nationality: "Indian",
      minPercentage: 55,
      maxFamilyIncome: null,
      minAge: null,
      maxAge: 28,
      disability: false,
      otherRequirements: "M.Sc. or equivalent; Indian citizen residing in India",
    },
    deadline: {
      applicationStartDate: null,
      applicationEndDate: null,
      typicalWindow: "Verify annually on CSIR-HRDG portal",
      isRecurring: true,
      isExactDateConfirmed: false,
    },
    requiredDocuments: [
      "M.Sc. certificate",
      "Category certificate",
      "ID proof",
      "Photograph",
    ],
    applicationProcess: "Apply on the CSIR-HRDG portal; appear for the NET exam.",
    source: {
      sourceName: "Council of Scientific and Industrial Research (CSIR), HRDG",
      sourceUrl: "https://csirhrdg.res.in/Home/Index/1/Default/3384/60",
      officialApplicationUrl: "https://csirhrdg.res.in/",
      sourceType: "government",
      lastVerifiedAt: VERIFIED_AT,
      contactPhone: "",
      contactEmail: "",
      contactWebsite: "https://csirhrdg.res.in/",
    },
    status: "active",
    isFeatured: false,
    displayOrder: 28,
    priority: 72,
    keywords: ["csir", "net", "jrf", "phd", "research", "science"],
  },
  {
    name: "IndianOil Academic Scholarship Scheme",
    shortDescription:
      "Scholarship for students pursuing Class 10+2 / ITI / Engineering / MBBS / MBA courses, with separate slabs based on education level.",
    description:
      "Class 10+/ITI: ₹12,000/yr; Engineering/MBBS/MBA: ₹36,000/yr (₹2,000/month). Mark relaxations: Gen 65%, SC/ST/OBC/Girls 55%, PwD 50%. Selection is centrally processed by SGM Technologies on behalf of IOCL.",
    scholarshipType: "merit",
    category: "industry_corporate",
    tags: ["iocl", "indian oil", "academic", "psu", "engineering", "medical"],
    amount: { min: 12000, max: 36000, currency: "INR", frequency: "annual" },
    eligibility: {
      educationLevels: ["class_12th", "diploma", "bachelor", "master"],
      streams: ["engineering", "medical", "any"],
      courses: ["Class 10+2", "ITI", "Engineering", "MBBS", "MBA"],
      categories: ["any"],
      gender: "any",
      states: [],
      nationality: "Indian",
      minPercentage: 65,
      maxFamilyIncome: 200000,
      minAge: null,
      maxAge: null,
      disability: false,
      otherRequirements: "Mark relaxations: SC/ST/OBC/Girls 55%, PwD 50%",
    },
    deadline: {
      applicationStartDate: null,
      applicationEndDate: null,
      typicalWindow: "September – November each year (verify on IOCL portal)",
      isRecurring: true,
      isExactDateConfirmed: false,
    },
    requiredDocuments: [
      "Mark sheets",
      "Income Certificate",
      "Bank passbook",
      "Aadhaar",
      "Photograph",
    ],
    applicationProcess:
      "Apply via Indian Oil's official scholarship portal; selection is processed centrally by SGM Technologies on behalf of IOCL.",
    source: {
      sourceName: "Indian Oil Corporation Limited (IOCL)",
      sourceUrl: "https://www.iocl.com/pages/indianoil-academic-scholarships-overview",
      officialApplicationUrl: "https://iocl.com/pages/indianoil-academic-scholarships-overview",
      sourceType: "organization",
      lastVerifiedAt: VERIFIED_AT,
      contactPhone: "",
      contactEmail: "",
      contactWebsite: "https://www.iocl.com/",
    },
    status: "active",
    isFeatured: false,
    displayOrder: 35,
    priority: 65,
    keywords: ["iocl", "indian oil", "psu", "scholarship", "engineering", "mbbs", "mba"],
  },

  // ============ RESEARCH ============
  {
    name: "Prime Minister's Research Fellowship (PMRF)",
    shortDescription:
      "Doctoral fellowship to attract the best talent into Ph.D. programs at IITs, IISc, IISERs, NITs, IIITs and other centrally-funded technical institutions.",
    description:
      "Award: ₹70,000/month (Yr 1–2); ₹75,000/month (Yr 3); ₹80,000/month (Yr 4–5); + ₹2,00,000/yr research grant (up to ₹10 lakh total); HRA additional if not hostel. Tenure: 5 years (4/5-year UG or integrated M.Tech); 3 years (post-Master's in engineering/tech); 5 years (2-year M.Sc.). Selection through written test/interview at designated IITs/IISc.",
    scholarshipType: "research",
    category: "research_fellowship",
    tags: ["pmrf", "phd", "research", "iit", "iisc", "iiser"],
    amount: { min: 840000, max: 960000, currency: "INR", frequency: "annual", note: "₹70-80k/mo + ₹2L/yr research grant" },
    eligibility: {
      educationLevels: ["phd"],
      streams: ["engineering", "medical", "pcm", "any"],
      courses: ["PhD at IITs/IISc/IISERs/NITs/IIITs"],
      categories: ["any"],
      gender: "any",
      states: [],
      nationality: "Indian",
      minPercentage: null,
      maxFamilyIncome: null,
      minAge: null,
      maxAge: null,
      disability: false,
      otherRequirements: "CGPA ≥ 8.0 (or equivalent); GATE ≥ 650 OR top rank in UGC/CSIR JRF; admission to PMRF-accepting institution",
    },
    deadline: {
      applicationStartDate: null,
      applicationEndDate: null,
      typicalWindow: "Cycle typically opens once a year; deadline around March–April",
      isRecurring: true,
      isExactDateConfirmed: false,
    },
    requiredDocuments: [
      "Degree certificate(s)",
      "GATE/CSIR-UGC NET scorecard",
      "PhD admission offer",
      "Research proposal",
      "Photograph",
    ],
    applicationProcess: "Apply on the PMRF portal; selection through written test and interview at designated institutions.",
    source: {
      sourceName: "Ministry of Education, Government of India",
      sourceUrl: "https://pmrf.in/documents/Overall-Guidelines.pdf",
      officialApplicationUrl: "https://pmrf.in/",
      sourceType: "government",
      lastVerifiedAt: VERIFIED_AT,
      contactPhone: "",
      contactEmail: "",
      contactWebsite: "https://pmrf.in/",
    },
    status: "active",
    isFeatured: true,
    displayOrder: 18,
    priority: 95,
    keywords: ["pmrf", "phd", "research", "iit", "iisc", "iiser", "doctoral"],
  },
  {
    name: "National Fellowship for Scheduled Caste Students (NFSC)",
    shortDescription:
      "Fellowship for SC students pursuing M.Phil. and/or Ph.D. in UGC-recognized institutions.",
    description:
      "Award: ₹37,000/month (JRF); ₹42,000/month (SRF); HRA, contingency, thesis printing, escort/reader assistance as per UGC norms. Open to those qualifying UGC-NET/CSIR-NET.",
    scholarshipType: "research",
    category: "research_fellowship",
    tags: ["nfsc", "sc", "phd", "mphil", "ugc", "research"],
    amount: { min: 444000, max: 504000, currency: "INR", frequency: "annual", note: "₹37k/mo JRF; ₹42k/mo SRF" },
    eligibility: {
      educationLevels: ["phd"],
      streams: ["any"],
      courses: [],
      categories: ["sc"],
      gender: "any",
      states: [],
      nationality: "Indian",
      minPercentage: 55,
      maxFamilyIncome: 600000,
      minAge: null,
      maxAge: null,
      disability: false,
      otherRequirements: "PG degree; must qualify UGC-NET/CSIR-NET or equivalent",
    },
    deadline: {
      applicationStartDate: null,
      applicationEndDate: null,
      typicalWindow: "Typically October–December via UGC portal",
      isRecurring: true,
      isExactDateConfirmed: false,
    },
    requiredDocuments: [
      "SC Caste Certificate",
      "Master's degree certificate",
      "NET scorecard",
      "PhD admission proof",
      "Income Certificate",
      "Aadhaar",
    ],
    applicationProcess: "Apply through UGC's official portal under the NFSC scheme.",
    source: {
      sourceName: "University Grants Commission (UGC)",
      sourceUrl: "https://socialjustice.gov.in/schemes/29",
      officialApplicationUrl: "https://www.ugc.ac.in/",
      sourceType: "government",
      lastVerifiedAt: VERIFIED_AT,
      contactPhone: "",
      contactEmail: "",
      contactWebsite: "https://www.ugc.gov.in/",
    },
    status: "active",
    isFeatured: false,
    displayOrder: 32,
    priority: 70,
    keywords: ["nfsc", "sc", "phd", "research", "ugc", "national fellowship"],
  },
  {
    name: "National Fellowship and Scholarship for Higher Education of ST Students (NFST)",
    shortDescription:
      "Fellowship for ST students pursuing M.Phil./Ph.D. (renamed from Rajiv Gandhi National Fellowship).",
    description: "Award: ₹37,000/month (JRF); ₹42,000/month (SRF); HRA + contingency as per UGC norms. 750 slots available.",
    scholarshipType: "research",
    category: "research_fellowship",
    tags: ["nfst", "st", "tribal", "phd", "ugc", "research"],
    amount: { min: 444000, max: 504000, currency: "INR", frequency: "annual", note: "₹37k/mo JRF; ₹42k/mo SRF" },
    eligibility: {
      educationLevels: ["phd"],
      streams: ["any"],
      courses: [],
      categories: ["st"],
      gender: "any",
      states: [],
      nationality: "Indian",
      minPercentage: 55,
      maxFamilyIncome: 600000,
      minAge: null,
      maxAge: null,
      disability: false,
      otherRequirements: "PG degree; admission to UGC-recognized institution",
    },
    deadline: {
      applicationStartDate: null,
      applicationEndDate: null,
      typicalWindow: "Verify annually — typically October–December",
      isRecurring: true,
      isExactDateConfirmed: false,
    },
    requiredDocuments: [
      "ST Caste Certificate",
      "Master's degree",
      "NET scorecard (if any)",
      "Income Certificate",
      "Aadhaar",
    ],
    applicationProcess: "Apply through NSP or UGC under the NFST scheme.",
    source: {
      sourceName: "Ministry of Tribal Affairs, Government of India (administered via UGC)",
      sourceUrl: "https://scholarships.gov.in/public/schemeGuidelines/tribalfellowshipguideline.pdf",
      officialApplicationUrl: "https://scholarships.gov.in/",
      sourceType: "government",
      lastVerifiedAt: VERIFIED_AT,
      contactPhone: "",
      contactEmail: "",
      contactWebsite: "https://tribal.nic.in/",
    },
    status: "active",
    isFeatured: false,
    displayOrder: 33,
    priority: 68,
    keywords: ["nfst", "st", "tribal", "phd", "research", "ugc"],
  },

  // ============ IITs / IIMs ============
  {
    name: "IIT Merit-cum-Means (MCM) Scholarship",
    shortDescription:
      "Institute-funded financial assistance for meritorious and economically-weaker students at IITs.",
    description:
      "Tuition fee waiver + ₹1,000–₹2,000/month (varies by IIT). IIT Delhi MCM ≈ ₹4,000/month for Gen/OBC/EWS. Free-messing facility for SC/ST. Each IIT sets its own threshold and amount. At IIT Bombay, MCM grants are outright (no bond).",
    scholarshipType: "merit_cum_need",
    category: "iit_iim",
    tags: ["iit", "mcm", "merit", "means", "engineering"],
    amount: { min: 12000, max: 48000, currency: "INR", frequency: "annual", note: "Tuition waiver + ₹1,000-4,000/mo" },
    eligibility: {
      educationLevels: ["bachelor", "master"],
      streams: ["engineering"],
      courses: ["Any IIT programme"],
      categories: ["any"],
      gender: "any",
      states: [],
      nationality: "Indian",
      minPercentage: null,
      maxFamilyIncome: 500000,
      minAge: null,
      maxAge: null,
      disability: false,
      otherRequirements: "Must be admitted to an IIT and clear the academic threshold",
    },
    deadline: {
      applicationStartDate: null,
      applicationEndDate: null,
      typicalWindow: "Within first year of enrolment at the IIT",
      isRecurring: true,
      isExactDateConfirmed: false,
    },
    requiredDocuments: [
      "Income Certificate",
      "Admission letter",
      "Bank passbook",
      "Aadhaar",
    ],
    applicationProcess: "Apply at the host IIT's academic office. Each IIT runs its own MCM process.",
    source: {
      sourceName: "Indian Institutes of Technology (IITs)",
      sourceUrl: "https://academics.iitd.ac.in/financial-assistance/",
      officialApplicationUrl: "https://acad.iitb.ac.in/academics/scholarship",
      sourceType: "university",
      lastVerifiedAt: VERIFIED_AT,
      contactPhone: "",
      contactEmail: "",
      contactWebsite: "https://home.iitd.ac.in/",
    },
    status: "active",
    isFeatured: false,
    displayOrder: 40,
    priority: 75,
    keywords: ["iit", "mcm", "merit", "means", "tuition waiver", "engineering"],
  },
  {
    name: "IIM Need-Based / Special Need-Based Scholarship",
    shortDescription:
      "Need-based financial aid for PGP students at IIMs based on family income and other means.",
    description:
      "IIMA also offers the Special Need-Based Scholarship (SNBS) and the Need cum Merit Scholarship (for income <₹4.5L). IIM Bangalore Need-Based Financial Aid: up to ₹1,75,000+ per year. Variable; covers partial/full tuition based on income tier.",
    scholarshipType: "need",
    category: "iit_iim",
    tags: ["iim", "pgp", "mba", "need-based", "snbs"],
    amount: { min: 100000, max: 500000, currency: "INR", frequency: "annual", note: "Slab-wise; up to full tuition" },
    eligibility: {
      educationLevels: ["master"],
      streams: ["management"],
      courses: ["PGP / PGP-FABM at IIMs"],
      categories: ["any"],
      gender: "any",
      states: [],
      nationality: "Indian",
      minPercentage: null,
      maxFamilyIncome: 1500000,
      minAge: null,
      maxAge: null,
      disability: false,
      otherRequirements: "Admitted to IIMA / IIMB PGP",
    },
    deadline: {
      applicationStartDate: null,
      applicationEndDate: null,
      typicalWindow: "Within first/second term of PGP",
      isRecurring: true,
      isExactDateConfirmed: false,
    },
    requiredDocuments: [
      "Income Certificate",
      "PGP admission letter",
      "Bank statements",
    ],
    applicationProcess: "Apply via the host IIM's financial aid office; submit income proof and other documents.",
    source: {
      sourceName: "Indian Institute of Management Ahmedabad (IIMA) / IIM Bangalore (IIMB)",
      sourceUrl: "https://www.iima.ac.in/programmes/pgp/financial-aid-scholarships",
      officialApplicationUrl: "https://www.iima.ac.in/programmes/pgp/financial-aid-scholarships",
      sourceType: "university",
      lastVerifiedAt: VERIFIED_AT,
      contactPhone: "",
      contactEmail: "",
      contactWebsite: "https://www.iima.ac.in/",
    },
    status: "active",
    isFeatured: true,
    displayOrder: 41,
    priority: 82,
    keywords: ["iim", "iima", "iimb", "pgp", "mba", "need-based", "snbs"],
  },

  // ============ STATE SCHOLARSHIPS ============
  {
    name: "Maharashtra Post-Matric Scholarship (MahaDBT)",
    shortDescription:
      "Post-matric scholarship for Maharashtra-domiciled SC/ST/OBC/VJNT/SBC/Minority students studying in recognised institutions in Maharashtra.",
    description:
      "Aadhaar mandatory. Multiple parallel schemes (Rajarshi Chhatrapati Shahu Maharaj Shikshan Shulk Shishyavrutti, etc.) may apply; check MahaDBT for the active set.",
    scholarshipType: "category",
    category: "state_government",
    tags: ["maharashtra", "post-matric", "sc", "st", "obc", "minority", "mahadbt"],
    amount: { min: 0, max: 100000, currency: "INR", frequency: "annual", note: "Tuition + maintenance + exam fee; slab varies" },
    eligibility: {
      educationLevels: ["class_12th", "diploma", "bachelor", "master", "phd"],
      streams: ["any"],
      courses: [],
      categories: ["sc", "st", "obc", "minority"],
      gender: "any",
      states: ["Maharashtra"],
      nationality: "Indian",
      minPercentage: null,
      maxFamilyIncome: 250000,
      minAge: null,
      maxAge: null,
      disability: false,
      otherRequirements: "Maharashtra-domiciled; ≥50% attendance",
    },
    deadline: {
      applicationStartDate: null,
      applicationEndDate: null,
      typicalWindow: "October – December each year (verify on MahaDBT)",
      isRecurring: true,
      isExactDateConfirmed: false,
    },
    requiredDocuments: [
      "Maharashtra Domicile Certificate",
      "Caste Certificate",
      "Income Certificate",
      "Mark sheets",
      "Fee receipt",
      "Aadhaar",
      "Bank passbook",
      "Bonafide",
    ],
    applicationProcess: "Apply via MahaDBT portal — login → schemes → choose the relevant scheme.",
    source: {
      sourceName: "Government of Maharashtra (Social Justice & Special Assistance; Tribal Development; Minority Development Departments)",
      sourceUrl: "https://mahadbt.maharashtra.gov.in/",
      officialApplicationUrl: "https://mahadbt.maharashtra.gov.in/",
      sourceType: "government",
      lastVerifiedAt: VERIFIED_AT,
      contactPhone: "",
      contactEmail: "",
      contactWebsite: "https://mahadbt.maharashtra.gov.in/",
    },
    status: "active",
    isFeatured: true,
    displayOrder: 50,
    priority: 80,
    keywords: ["maharashtra", "post-matric", "sc", "st", "obc", "minority", "mahadbt"],
  },
  {
    name: "Bihar Post-Matric Scholarship (SC / ST / BC / EBC)",
    shortDescription:
      "Post-matric scholarship for Bihar-domiciled SC/ST/BC/EBC students studying in recognised institutions.",
    description:
      "Up to ₹50,000 (varies by course level; tuition + maintenance + other allowances). Earlier scholarship.bih.nic.in was redirected to pmsonline.bihar.gov.in.",
    scholarshipType: "category",
    category: "state_government",
    tags: ["bihar", "post-matric", "sc", "st", "bc", "ebc"],
    amount: { min: 0, max: 50000, currency: "INR", frequency: "annual" },
    eligibility: {
      educationLevels: ["class_12th", "diploma", "bachelor", "master"],
      streams: ["any"],
      courses: [],
      categories: ["sc", "st", "obc"],
      gender: "any",
      states: ["Bihar"],
      nationality: "Indian",
      minPercentage: null,
      maxFamilyIncome: 250000,
      minAge: null,
      maxAge: null,
      disability: false,
      otherRequirements: "Bihar-domiciled; passed previous qualifying exam",
    },
    deadline: {
      applicationStartDate: null,
      applicationEndDate: null,
      typicalWindow: "August – November each year (verify on PMS portal)",
      isRecurring: true,
      isExactDateConfirmed: false,
    },
    requiredDocuments: [
      "Bihar Domicile",
      "Caste Certificate",
      "Income Certificate",
      "Mark sheets",
      "Fee receipt",
      "Aadhaar",
      "Bank passbook",
    ],
    applicationProcess: "Apply via the Bihar Post-Matric Scholarship Online portal.",
    source: {
      sourceName: "Government of Bihar (Welfare Department; BC & EBC Welfare Department)",
      sourceUrl: "https://pmsonline.bihar.gov.in/",
      officialApplicationUrl: "https://pmsonline.bihar.gov.in/",
      sourceType: "government",
      lastVerifiedAt: VERIFIED_AT,
      contactPhone: "",
      contactEmail: "",
      contactWebsite: "https://pmsonline.bihar.gov.in/",
    },
    status: "active",
    isFeatured: false,
    displayOrder: 51,
    priority: 70,
    keywords: ["bihar", "post-matric", "sc", "st", "bc", "ebc"],
  },
  {
    name: "Tamil Nadu Post-Matric Scholarship (ADW-201 / ADW-202 / MCW-201 / BCW-202)",
    shortDescription:
      "Post-matric scholarships for Tamil Nadu-domiciled SC/ST/MBC/BC students pursuing higher education after Class 10.",
    description:
      "Tuition fee + hostel fees + academic allowance (slab by scheme). Apply via TN SSP or TNeSevai. Scheme codes (ADW-201, MCW-201, etc.) determine category.",
    scholarshipType: "category",
    category: "state_government",
    tags: ["tamil nadu", "post-matric", "sc", "st", "obc", "ssp", "tnesevai"],
    amount: { min: 0, max: 100000, currency: "INR", frequency: "annual", note: "Tuition + hostel + academic allowance" },
    eligibility: {
      educationLevels: ["class_12th", "diploma", "bachelor", "master"],
      streams: ["any"],
      courses: [],
      categories: ["sc", "st", "obc"],
      gender: "any",
      states: ["Tamil Nadu"],
      nationality: "Indian",
      minPercentage: null,
      maxFamilyIncome: 250000,
      minAge: null,
      maxAge: null,
      disability: false,
      otherRequirements: "Tamil Nadu-domiciled",
    },
    deadline: {
      applicationStartDate: null,
      applicationEndDate: null,
      typicalWindow: "Verify annually via TN SSP",
      isRecurring: true,
      isExactDateConfirmed: false,
    },
    requiredDocuments: [
      "Tamil Nadu Domicile",
      "Community Certificate",
      "Income Certificate",
      "Mark sheets",
      "Fee receipt",
      "Aadhaar",
      "Bank passbook",
    ],
    applicationProcess: "Apply via TN SSP (ssp.tn.gov.in) or TNeSevai (tnesevai.tn.gov.in).",
    source: {
      sourceName: "Government of Tamil Nadu (Adi Dravidar & Tribal Welfare; BC/MBC Welfare Departments)",
      sourceUrl: "https://ssp.tn.gov.in/",
      officialApplicationUrl: "https://ssp.tn.gov.in/",
      sourceType: "government",
      lastVerifiedAt: VERIFIED_AT,
      contactPhone: "",
      contactEmail: "",
      contactWebsite: "https://www.tnesevai.tn.gov.in/",
    },
    status: "active",
    isFeatured: false,
    displayOrder: 52,
    priority: 70,
    keywords: ["tamil nadu", "post-matric", "sc", "st", "obc", "ssp"],
  },
  {
    name: "Karnataka State Scholarship Portal (SSP) Post-Matric Scholarship",
    shortDescription:
      "Post-matric scholarship for Karnataka-domiciled SC/ST/OBC students via the unified State Scholarship Portal.",
    description: "Tuition fee + maintenance + other allowances (slab by category & course). Earlier karepass.careout.karnataka.gov.in is being consolidated into ssp.karnataka.gov.in.",
    scholarshipType: "category",
    category: "state_government",
    tags: ["karnataka", "ssp", "post-matric", "sc", "st", "obc"],
    amount: { min: 0, max: 100000, currency: "INR", frequency: "annual", note: "Tuition + maintenance + other allowances" },
    eligibility: {
      educationLevels: ["class_12th", "diploma", "bachelor", "master"],
      streams: ["any"],
      courses: [],
      categories: ["sc", "st", "obc"],
      gender: "any",
      states: ["Karnataka"],
      nationality: "Indian",
      minPercentage: null,
      maxFamilyIncome: 250000,
      minAge: null,
      maxAge: null,
      disability: false,
      otherRequirements: "Karnataka-domiciled; passed previous qualifying exam",
    },
    deadline: {
      applicationStartDate: null,
      applicationEndDate: null,
      typicalWindow: "Verify annually via SSP portal",
      isRecurring: true,
      isExactDateConfirmed: false,
    },
    requiredDocuments: [
      "Karnataka Domicile",
      "Caste Certificate",
      "Income Certificate",
      "Mark sheets",
      "Fee receipt",
      "Aadhaar",
      "Bank passbook",
    ],
    applicationProcess: "Apply via the Karnataka State Scholarship Portal (SSP).",
    source: {
      sourceName: "Government of Karnataka (Backward Classes Welfare; Social Welfare Departments)",
      sourceUrl: "https://ssp.karnataka.gov.in/",
      officialApplicationUrl: "https://ssp.karnataka.gov.in/",
      sourceType: "government",
      lastVerifiedAt: VERIFIED_AT,
      contactPhone: "",
      contactEmail: "",
      contactWebsite: "https://ssp.karnataka.gov.in/",
    },
    status: "active",
    isFeatured: false,
    displayOrder: 53,
    priority: 68,
    keywords: ["karnataka", "ssp", "post-matric", "sc", "st", "obc"],
  },

  // ============ PRIVATE / FOUNDATION ============
  {
    name: "Reliance Foundation Undergraduate Scholarship",
    shortDescription:
      "Scholarship for meritorious Indian students from lower/middle-income households pursuing undergraduate degrees at any accredited Indian institution.",
    description:
      "Award: Up to ₹2,00,000 per student (UG cycle). Includes mentorship by industry experts, career guidance, networking, and workshops. Separate PG scholarship also offered.",
    scholarshipType: "merit_cum_need",
    category: "private_foundation",
    tags: ["reliance", "foundation", "ug", "scholarship", "mentorship"],
    amount: { min: 0, max: 200000, currency: "INR", frequency: "annual", note: "Up to ₹2,00,000 per UG cycle" },
    eligibility: {
      educationLevels: ["bachelor"],
      streams: ["any"],
      courses: [],
      categories: ["any"],
      gender: "any",
      states: [],
      nationality: "Indian",
      minPercentage: 60,
      maxFamilyIncome: 1500000,
      minAge: null,
      maxAge: null,
      disability: false,
      otherRequirements: "1st year of UG full-time degree; ≥60% in Class 12",
    },
    deadline: {
      applicationStartDate: null,
      applicationEndDate: null,
      typicalWindow: "Verify annually on Reliance Foundation portal",
      isRecurring: true,
      isExactDateConfirmed: false,
    },
    requiredDocuments: [
      "Class 12 marksheet",
      "UG admission proof",
      "Income Certificate",
      "ID",
      "Bank details",
    ],
    applicationProcess: "Apply on the Reliance Foundation scholarship portal.",
    source: {
      sourceName: "Reliance Foundation",
      sourceUrl: "https://www.scholarships.reliancefoundation.org/",
      officialApplicationUrl: "https://www.scholarships.reliancefoundation.org/UG_Scholarship",
      sourceType: "foundation",
      lastVerifiedAt: VERIFIED_AT,
      contactPhone: "",
      contactEmail: "",
      contactWebsite: "https://www.reliancefoundation.org/",
    },
    status: "active",
    isFeatured: true,
    displayOrder: 60,
    priority: 84,
    keywords: ["reliance foundation", "ug scholarship", "merit", "need", "mentorship"],
  },
  {
    name: "Aditya Birla Group Scholarship",
    shortDescription:
      "Need-based scholarship for students admitted to premier institutions (IIMs, IITs, BITS Pilani, XLRI, NLUs) covering Engineering, Management, and Law streams.",
    description:
      "Engineering (IITs/BITS): ₹1,50,000; Management (IIMs/XLRI): ₹3,00,000; Law (NLU): ₹1,80,000 or fee at actuals. Established 1999. Distinct from the broader 'Aditya Birla Capital Scholarship' (run via Buddy4Study for Class 9–12 and other categories).",
    scholarshipType: "need",
    category: "private_foundation",
    tags: ["aditya birla", "premier institute", "iit", "iim", "bits", "nlu", "law", "engineering"],
    amount: { min: 150000, max: 300000, currency: "INR", frequency: "full_course", note: "Per stream: ₹1.5L/₹1.8L/₹3L" },
    eligibility: {
      educationLevels: ["bachelor", "master"],
      streams: ["engineering", "law", "management"],
      courses: ["Premier institutes — IITs, IIMs, BITS, XLRI, NLUs"],
      categories: ["any"],
      gender: "any",
      states: [],
      nationality: "Indian",
      minPercentage: 60,
      maxFamilyIncome: 600000,
      minAge: null,
      maxAge: null,
      disability: false,
      otherRequirements: "Min 60% in most recent academic year; admission at a notified institute",
    },
    deadline: {
      applicationStartDate: null,
      applicationEndDate: null,
      typicalWindow: "October – November each year (verify on official portal)",
      isRecurring: true,
      isExactDateConfirmed: false,
    },
    requiredDocuments: [
      "Marksheets",
      "Admission letter",
      "Income Certificate",
      "ID",
      "Photograph",
    ],
    applicationProcess: "Apply on the Aditya Birla Group Scholarship portal.",
    source: {
      sourceName: "Aditya Birla Group (Aditya Birla Foundation)",
      sourceUrl: "https://www.adityabirlascholars.net/the-scholarship/",
      officialApplicationUrl: "https://www.adityabirlascholars.net/the-scholarship/eligibility-application-process/",
      sourceType: "foundation",
      lastVerifiedAt: VERIFIED_AT,
      contactPhone: "",
      contactEmail: "",
      contactWebsite: "https://www.adityabirlascholars.net/",
    },
    status: "active",
    isFeatured: true,
    displayOrder: 61,
    priority: 85,
    keywords: ["aditya birla", "premier institute", "iit", "iim", "bits", "law", "management"],
  },
  {
    name: "Sitaram Jindal Foundation Scholarship",
    shortDescription:
      "Scholarship for meritorious and financially-weaker students studying in Class 11 onwards up to PG level (including Engineering and Medical).",
    description:
      "Slab-wise award: Class XI–XII ₹500/month; ITI/Diploma/UG/PG (Cat A) ₹1,200/month; up to ₹3,200/month max. Age cap: 30 years. Official domain: sitaramjindalfoundation.org.",
    scholarshipType: "merit_cum_need",
    category: "private_foundation",
    tags: ["jindal", "sitaram jindal", "foundation", "merit", "means"],
    amount: { min: 6000, max: 38400, currency: "INR", frequency: "annual", note: "Slab-wise: ₹500-₹3,200/month" },
    eligibility: {
      educationLevels: ["class_12th", "diploma", "bachelor", "master"],
      streams: ["engineering", "medical", "any"],
      courses: [],
      categories: ["any"],
      gender: "any",
      states: [],
      nationality: "Indian",
      minPercentage: 55,
      maxFamilyIncome: 400000,
      minAge: null,
      maxAge: 30,
      disability: false,
      otherRequirements: "Female: ≥55% in previous exam; Male: ≥60% in previous exam",
    },
    deadline: {
      applicationStartDate: null,
      applicationEndDate: null,
      typicalWindow: "Verify annually on the foundation site",
      isRecurring: true,
      isExactDateConfirmed: false,
    },
    requiredDocuments: [
      "Marksheets",
      "Income Certificate",
      "Course fee receipt",
      "Bonafide",
      "Bank passbook",
      "ID",
    ],
    applicationProcess: "Apply on the Sitaram Jindal Foundation portal.",
    source: {
      sourceName: "Sitaram Jindal Foundation (SJF)",
      sourceUrl: "https://www.sitaramjindalfoundation.org/scholarships.php",
      officialApplicationUrl: "https://www.sitaramjindalfoundation.org/",
      sourceType: "foundation",
      lastVerifiedAt: VERIFIED_AT,
      contactPhone: "Check foundation site",
      contactEmail: "",
      contactWebsite: "https://www.sitaramjindalfoundation.org/",
    },
    status: "active",
    isFeatured: false,
    displayOrder: 65,
    priority: 65,
    keywords: ["jindal", "sitaram jindal", "foundation", "scholarship", "merit", "means"],
  },
  {
    name: "SOF Academic Excellence Scholarship (AES)",
    shortDescription:
      "Scholarship awarded to high-performing students in SOF Olympiads (NSO, IMO, IEO, IGKO, ICSO) demonstrating academic excellence.",
    description: "Award: ₹5,000 + Trophy per student (slab can change year-to-year). ~160 scholarships typically awarded; tied rank holders share the prize pool equally.",
    scholarshipType: "merit",
    category: "olympiad",
    tags: ["sof", "olympiad", "nso", "imo", "ieo", "igko", "icso", "academic excellence"],
    amount: { min: 5000, max: 5000, currency: "INR", frequency: "one_time" },
    eligibility: {
      educationLevels: ["class_10th", "class_12th"],
      streams: ["any"],
      courses: [],
      categories: ["any"],
      gender: "any",
      states: [],
      nationality: "Indian",
      minPercentage: null,
      maxFamilyIncome: null,
      minAge: null,
      maxAge: null,
      disability: false,
      otherRequirements: "Top rank in SOF Olympiad exams",
    },
    deadline: {
      applicationStartDate: null,
      applicationEndDate: null,
      typicalWindow: "Per olympiad cycle — typically March–May",
      isRecurring: true,
      isExactDateConfirmed: false,
    },
    requiredDocuments: [
      "School ID",
      "Marksheet",
      "Olympiad participation proof",
    ],
    applicationProcess: "Top-performing SOF Olympiad rankers are awarded automatically; verify on the SOF website.",
    source: {
      sourceName: "Science Olympiad Foundation (SOF)",
      sourceUrl: "https://sofworld.org/academic-excellence-scholarship-aes",
      officialApplicationUrl: "https://sofworld.org/scholarships",
      sourceType: "organization",
      lastVerifiedAt: VERIFIED_AT,
      contactPhone: "",
      contactEmail: "",
      contactWebsite: "https://sofworld.org/",
    },
    status: "active",
    isFeatured: false,
    displayOrder: 70,
    priority: 55,
    keywords: ["sof", "olympiad", "nso", "imo", "ieo", "academic excellence"],
  },
  {
    name: "Aga Khan Foundation International Scholarship Programme (AKF ISP)",
    shortDescription:
      "Need-based scholarship for outstanding students from developing countries (including India) to pursue postgraduate studies abroad.",
    description:
      "Covers tuition + living expenses (50% grant, 50% loan; 50% repayable on favourable terms post-studies). Highly competitive. Age preference: under 30. Open to all developing-country nationals — not restricted to any community.",
    scholarshipType: "need",
    category: "international",
    tags: ["aga khan", "akf", "international", "postgraduate", "abroad"],
    amount: { min: 1000000, max: 5000000, currency: "INR", frequency: "full_course", note: "Tuition + living expenses (50% grant, 50% loan)" },
    eligibility: {
      educationLevels: ["master", "phd"],
      streams: ["any"],
      courses: [],
      categories: ["any"],
      gender: "any",
      states: [],
      nationality: "Any developing-country national residing in India",
      minPercentage: null,
      maxFamilyIncome: null,
      minAge: null,
      maxAge: 30,
      disability: false,
      otherRequirements: "Demonstrated financial need; excellent academic record; Bachelor's degree or equivalent",
    },
    deadline: {
      applicationStartDate: null,
      applicationEndDate: null,
      typicalWindow: "Apply once a year — usually March–July (Indian applicants contact AKF India office)",
      isRecurring: true,
      isExactDateConfirmed: false,
    },
    requiredDocuments: [
      "Statement of Purpose",
      "Academic transcripts",
      "Admission offer (if any)",
      "Reference letters",
      "ID",
      "Income proof",
    ],
    applicationProcess: "Apply via the AKF International Scholarship Programme portal; Indian applicants coordinate with the AKF India office.",
    source: {
      sourceName: "Aga Khan Foundation (AKF) / Aga Khan Development Network (AKDN)",
      sourceUrl: "https://the.akdn/en/what-we-do/developing-human-capacity/education/international-scholarships",
      officialApplicationUrl: "https://the.akdn/en/what-we-do/developing-human-capacity/education/international-scholarships",
      sourceType: "foundation",
      lastVerifiedAt: VERIFIED_AT,
      contactPhone: "",
      contactEmail: "",
      contactWebsite: "https://the.akdn/",
    },
    status: "active",
    isFeatured: true,
    displayOrder: 62,
    priority: 83,
    keywords: ["aga khan", "akf", "international scholarship", "postgraduate", "abroad"],
  },
  {
    name: "Inlaks Shivdasani Foundation Scholarship",
    shortDescription:
      "Scholarship for Indian residents to pursue Master's or Ph.D. programmes at top-ranked foreign universities.",
    description:
      "Award: Up to USD 100,000 (covers tuition + return airfare + living expenses + health insurance + settling-in allowance + books/equipment). Up to 80 Inlaks scholarships per year across all programmes. Foundation established 1975.",
    scholarshipType: "merit",
    category: "international",
    tags: ["inlaks", "shivdasani", "foreign university", "masters", "phd abroad"],
    amount: { min: 5000000, max: 8500000, currency: "INR", frequency: "full_course", note: "Up to USD 100,000 ≈ ₹85L" },
    eligibility: {
      educationLevels: ["master", "phd"],
      streams: ["any"],
      courses: ["Top foreign university programmes (~top 50 QS/THE/US News by subject)"],
      categories: ["any"],
      gender: "any",
      states: [],
      nationality: "Indian",
      minPercentage: null,
      maxFamilyIncome: 2000000,
      minAge: null,
      maxAge: 30,
      disability: false,
      otherRequirements: "Degree from recognised Indian institution; under 30 years; admission offer at top foreign university",
    },
    deadline: {
      applicationStartDate: null,
      applicationEndDate: null,
      typicalWindow: "March–April; interviews June–July; results August (verify annually)",
      isRecurring: true,
      isExactDateConfirmed: false,
    },
    requiredDocuments: [
      "Statement of Purpose",
      "Academic transcripts",
      "Admission letter",
      "2–3 reference letters",
      "CV",
      "ID",
    ],
    applicationProcess: "Apply via the Inlaks Shivdasani Foundation portal.",
    source: {
      sourceName: "Inlaks Shivdasani Foundation, Mumbai",
      sourceUrl: "https://inlaks.com/scholarships/",
      officialApplicationUrl: "https://inlaks.com/",
      sourceType: "foundation",
      lastVerifiedAt: VERIFIED_AT,
      contactPhone: "",
      contactEmail: "",
      contactWebsite: "https://inlaks.com/",
    },
    status: "active",
    isFeatured: true,
    displayOrder: 63,
    priority: 88,
    keywords: ["inlaks", "shivdasani", "foreign university", "masters", "phd"],
  },
  {
    name: "IISER Aptitude Test (IAT) — KVPY replaced",
    shortDescription:
      "Admission + scholarship pathway to IISERs' 5-Year BS-MS Dual Degree; replaced KVPY since KVPY was discontinued.",
    description:
      "KVPY has been discontinued. Top IAT rankers receive INSPIRE-equivalent scholarships (~₹5,000/month fellowship; verify against current IISER notification). Last IAT cycle: June 2024 (last date 13 May 2024).",
    scholarshipType: "merit",
    category: "central_government",
    tags: ["iiser", "iat", "kvpy", "bs-ms", "science", "scholarship"],
    amount: { min: 5000, max: 5000, currency: "INR", frequency: "monthly", note: "Verify against current IISER notification" },
    eligibility: {
      educationLevels: ["bachelor", "master"],
      streams: ["pcm"],
      courses: ["5-Year BS-MS Dual Degree at IISERs"],
      categories: ["any"],
      gender: "any",
      states: [],
      nationality: "Indian",
      minPercentage: null,
      maxFamilyIncome: null,
      minAge: null,
      maxAge: null,
      disability: false,
      otherRequirements: "Top score in IAT / JEE Advanced / State Board Channel",
    },
    deadline: {
      applicationStartDate: null,
      applicationEndDate: null,
      typicalWindow: "April–May application; June test (verify annually)",
      isRecurring: true,
      isExactDateConfirmed: false,
    },
    requiredDocuments: [
      "Class 12 marksheet",
      "Scorecard (IAT / JEE Advanced / KVPY)",
      "ID",
    ],
    applicationProcess: "Apply on the IISER Admissions portal; appear for the IAT or use JEE Advanced / State Board channel.",
    source: {
      sourceName: "Indian Institutes of Science Education and Research (IISERs)",
      sourceUrl: "https://www.iiserkol.ac.in/old/en/academic/programmes/5-year-bs-ms-dual-degree-programme/",
      officialApplicationUrl: "https://www.iiseradmission.in/",
      sourceType: "university",
      lastVerifiedAt: VERIFIED_AT,
      contactPhone: "",
      contactEmail: "",
      contactWebsite: "https://www.iiseradmission.in/",
    },
    status: "active",
    isFeatured: false,
    displayOrder: 36,
    priority: 72,
    keywords: ["iiser", "iat", "kvpy", "bs-ms", "science", "scholarship"],
  },
];

// ─── Run ───────────────────────────────────────────────────────────────

async function run() {
  const args = process.argv.slice(2);
  const force = args.includes("--force");
  const refreshDates = args.includes("--refresh-dates");

  await connectDB();

  const admin = await Admin.findOne({ role: "superadmin" });
  if (!admin) {
    logger.error("No superadmin found — please run npm run seed first");
    process.exit(1);
  }
  const adminId = admin._id;

  const records = getScholarships().map((r) => ({
    ...r,
    createdBy: adminId,
    updatedBy: adminId,
  }));

  if (refreshDates) {
    // Only refresh lastVerifiedAt for existing records
    let updated = 0;
    for (const r of records) {
      const res = await Scholarship.updateOne(
        { name: r.name },
        { $set: { "source.lastVerifiedAt": VERIFIED_AT } }
      );
      if (res.modifiedCount > 0) updated += 1;
    }
    logger.success(`Refreshed lastVerifiedAt on ${updated} records`);
    process.exit(0);
  }

  if (force) {
    logger.info("Force flag set — deleting existing scholarships");
    const del = await Scholarship.deleteMany({});
    logger.success(`Deleted ${del.deletedCount} existing records`);
  }

  let inserted = 0;
  let updated = 0;
  for (const r of records) {
    const existing = await Scholarship.findOne({ name: r.name });
    if (existing) {
      // Update only the fields that are part of the verified dataset.
      const updatable = [
        "shortDescription",
        "description",
        "scholarshipType",
        "category",
        "tags",
        "amount",
        "eligibility",
        "deadline",
        "requiredDocuments",
        "applicationProcess",
        "source",
        "isFeatured",
        "displayOrder",
        "priority",
        "keywords",
      ];
      for (const k of updatable) {
        if (r[k] !== undefined) existing[k] = r[k];
      }
      existing.updatedBy = adminId;
      await existing.save();
      updated += 1;
    } else {
      await Scholarship.create(r);
      inserted += 1;
    }
  }

  const total = await Scholarship.countDocuments();
  logger.success(`Inserted: ${inserted}, Updated: ${updated}, Total in DB: ${total}`);

  process.exit(0);
}

run().catch((err) => {
  logger.error("Seed failed", err);
  process.exit(1);
});
