const AMENITIES = [
  { id: 1, key: "wifi", label: "Wi-Fi" },
  { id: 2, key: "food", label: "Food / Mess" },
  { id: 3, key: "laundry", label: "Laundry" },
  { id: 4, key: "parking", label: "Parking" },
  { id: 5, key: "power_backup", label: "Power Backup" },
  { id: 6, key: "housekeeping", label: "Housekeeping" },
  { id: 7, key: "cctv", label: "CCTV Surveillance" },
  { id: 8, key: "warden", label: "Warden / Caretaker" },
  { id: 9, key: "lift", label: "Lift" },
  { id: 10, key: "ro_water", label: "RO Drinking Water" },
  { id: 11, key: "geyser", label: "Geyser" },
  { id: 12, key: "ac", label: "Air Conditioning" },
  { id: 13, key: "non_ac", label: "Non-AC Rooms" },
  { id: 14, key: "study_room", label: "Study Room" },
  { id: 15, key: "common_tv", label: "Common TV Room" },
  { id: 16, key: "fridge", label: "Refrigerator" },
  { id: 17, key: "gym", label: "Gym" },
  { id: 18, key: "security_guard", label: "Security Guard" },
  { id: 19, key: "biometric_entry", label: "Biometric Entry" },
  { id: 20, key: "visitor_allowed", label: "Visitors Allowed" },
  { id: 21, key: "clean_drinking_water", label: "Clean Drinking Water" },
  { id: 22, key: "fire_safety", label: "Fire Safety" },
  { id: 23, key: "first_aid", label: "First Aid" },
  { id: 24, key: "daily_cleaning", label: "Daily Cleaning" },
  { id: 25, key: "bed_with_mattress", label: "Bed with Mattress" },
  { id: 26, key: "cupboard", label: "Cupboard / Almirah" },
  { id: 27, key: "study_table", label: "Study Table" },
  { id: 28, key: "balcony", label: "Balcony" },
  { id: 29, key: "attached_bathroom", label: "Attached Bathroom" },
  { id: 30, key: "western_toilet", label: "Western Toilet" },
  { id: 31, key: "indian_toilet", label: "Indian Toilet" },
  { id: 32, key: "hot_water", label: "Hot Water" },
  { id: 33, key: "cold_water", label: "Cold Water" },
  { id: 34, key: "wifi_24x7", label: "24x7 Wi-Fi" },
  { id: 35, key: "meal_veg", label: "Veg Meals" },
  { id: 36, key: "meal_non_veg", label: "Non-Veg Meals" },
  { id: 37, key: "tiffin_service", label: "Tiffin Service" },
  { id: 38, key: "generator", label: "Generator Backup" },
  { id: 39, key: "washing_machine", label: "Washing Machine" },
  { id: 40, key: "iron_facility", label: "Iron Facility" },
];

export const AMENITY_KEYS = AMENITIES.map((a) => a.key);

export default AMENITIES;